substitutions:
  devicename: espsaltlevel
  api_key: !secret api_key_espsaltlevel
  ota_password: !secret ota_password_espsaltlevel

packages:
  wifi: !include inc/wifi.yaml
  auth: !include inc/auth.yaml

esphome:
  name: $devicename

esp8266:
  board: d1_mini

logger:
  level: INFO

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s
  sleep_duration: 15min

i2c:

binary_sensor:
  - platform: homeassistant
    id: sleep_inhibited
    entity_id: input_boolean.inhibit_${devicename}_sleep
    publish_initial_state: true
    on_press:
      then:
        - logger.log: Deep sleep inhibited from Home Assistant
        - deep_sleep.prevent: deep_sleep_1
    on_release:
      then:
        - logger.log: Deep sleep enabled from Home Assistant
        - deep_sleep.allow: deep_sleep_1

sensor:
  - platform: adc
    name: Tension batterie ${devicename}
    pin: A0
    samples: 5
    update_interval: 2s
    icon: mdi:battery
    device_class: voltage
    unit_of_measurement: V
    filters:
      - multiply: 4.4
  - platform: vl53l0x
    name: Hauteur sel adoucisseur
    update_interval: 2s
    device_class: distance
