substitutions:
  devicename: espsaltlevel
  api_key: !secret api_key_espsaltlevel
  ota_password: !secret ota_password_espsaltlevel

packages:
  wifi: !include inc/wifi.yaml
  auth: !include inc/auth.yaml

esphome:
  name: $devicename

esp8266:
  board: esp_wroom_02

logger:
  level: INFO

deep_sleep:
  id: deep_sleep_1
  run_duration: 10s
  sleep_duration: 15min

i2c:
  sda: GPIO4
  scl: GPIO5

binary_sensor:
  - platform: homeassistant
    id: deep_sleep_inhibit
    name: Inhibit deep sleep from Home Assistant
    entity_id: input_boolean.inhibition_sommeil_espsaltlevel
    publish_initial_state: true
    on_press:
      then:
        - logger.log: Deep sleep inhibited from Home Assistant
        - deep_sleep.prevent: deep_sleep_1
    on_release:
      then:
        - logger.log: Deep sleep enabled from Home Assistant
        - deep_sleep.allow: deep_sleep_1

sensor:
  - platform: adc
    name: Tension MCU ${devicename}
    pin: VCC
    samples: 5
    update_interval: 2s
  - platform: vl53l0x
    name: Hauteur sel adoucisseur
    update_interval: 2s
    device_class: distance
